# Generated by Django 5.2.1 on 2025-05-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={},
        ),
        migrations.RemoveField(
            model_name='editora',
            name='site',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
